<!DOCTYPE html>
<html lang="en-gb">
<?php 
    $this->open("head");
        require_once("{$this->partial['header']}");
    $this->close("head");
    $clapOMeterBox = false;
?><body class="paper-white ink-bright-black">
<?php
    $this->open("div", "content", "container");

        if(!empty($this->partial['navbar'])):
            require_once("{$this->partial['navbar']}");
        endif;

        if(!empty($this->flash->message)):
            $this->open("div", "flash", array("container", "flash"))
                ->p()->id("flash-message")->addClass(array("flash-bg", "green"))->closeElement()
                    ->text($this->flash->message)
                ->close("p")
            ->close("div");
        endif;

        $this->h(1, $this->header, "header")->h(3, $this->subHeader, "sub_header");
        
        $this->p()->id("table-of-contents")->addClass(array("col-xs-12", "h3", "clearfix", "ink-bright-red"))->closeElement()
            ->text("Table of Contents")
        ->close("p");
        
        $this->p()->addClass(array("col-xs-12", "h5", "clearfix", "ink-bright-yellow"))->closeElement()
            ->text("Click to select the review to the game the you want to read.")
        ->close("p");
        
        $this->open("div", "", array("col-xs-12", "clearfix"));
            $this->open("ul", '', array("unstlyed"))
            ->open("li", "", "clearfix")
                ->a('', "{$this->host}/reviews", '', '', 'strong ink-bright-green clearfix table-of-contents-link', '' , true)
                    ->text("&laquo;&nbsp;EXIT")
                ->close("a")
            ->close("li");
            foreach($this->tableOfContents as $id => $name):
                $this->open("li", "", "clearfix");
                    $this->a('', "#{$id}", '', '', 'strong ink-bright-green clearfix table-of-contents-link', '' , true)
                        ->text("&raquo;&nbsp;{$name}")
                    ->close("a");
                $this->close("li");
            endforeach;
            $this->close("ul");
        $this->close("div");
        
        $hrCounter = 1;
        $hrDirection = 1;
        
        include($this->partial['hrcolours']);
        
        foreach($this->content as $content):
            $this->p()->id($this->lib->convertToHtmlId("{$content['title']}"))->addClass("h2")->closeElement()->text($content['title'])->close("p");
            $this->p()->addClass(array("h3", "ink-cyan"))->closeElement()->text("In a nut-shell: {$content['sub-header']}")->close("p");
            $this->p()->addClass(array("h5", "ink-cyan"))->closeElement()->text("Developer: {$content['developer']}")->close("p");
            
            if($content['yawn-sinclair-mega-game'] === 1):
                $this->p()->addClass(array("h4", "ink-red"))->closeElement()->text("Yawn Sinclair MegaGame");
            endif;
            
            foreach($content['content'] as $reviewText):
                $this->p()->closeElement()->text("{$reviewText}")->close("p");
            endforeach;
            
            if($clapOMeterBox === false):
                $this->open("div", '', array("col-xs-12", "clearfix"));
                $clapOMeterBox = true;
            endif;
            
            $this->open("div", '', array("col-xs-12", "col-md-6", "pull-left"));
                $this->open("p", '', "review-screen-shot");
                    $this->img(
                        "",
                        "{$content['screen-shot']['location']}{$content['screen-shot']['file-name']}",
                        "{$content['screen-shot']['width']}",
                        "{$content['screen-shot']['height']}",
                        "{$content['screen-shot']['alt']}",
                        "{$content['screen-shot']['class']} review-screen-shot"
                    );
                $this->close("p");
            $this->close("div");
            
            foreach($content['cgc-clapometer'] as $key => $ratings):
                if($key == 'summary'):
                $this->open("div", '', array("col-xs-12", "col-md-6", "pull-right"))->open("div", '', "clapometer-box")->p()->addClass(["h2","ink-yellow","clapometer"])->closeElement()->text("CGC CLAPOMETER")->p()->addClass("clapometer-summary")->closeElement()->text("<strong class=\"ink-blue\">" . ucFirst($key) . ":</strong>&nbsp;{$ratings}")->close("p");
                    continue;
                elseif($key != 'sundry'):
                    $this->p()->addClass("clapometer-ratings")->closeElement()->text("<strong class=\"ink-blue\">" . ucFirst($key) . ":</strong> &nbsp;");
                    $this->open("span", '', "pull-right");
                        for($i = 1; $i <= 10; $i++):
                            if($i <= $ratings):
                                $this->text("<i class=\"clapometer-point\">&nbsp;&nbsp;&nbsp;</i>");
                            else:
                                $this->text("<i class=\"clapometer-pointless\">&nbsp;&nbsp;&nbsp;</i>");
                            endif;
                        endfor;
                    $this->close("span");
                    $this->close("p");
                elseif($key == 'sundry'):
                    foreach($ratings as $textSundry):
                        $this->p()->addClass("ink-red")->closeElement()->text($textSundry)->close("p");
                    endforeach;
                    $this->close("div")->close("div");
                endif;
            endforeach;
            
            if($clapOMeterBox === true):
                $this->p()->addClass(array("col-xs-6", "pull-right"))->closeElement()->text('<a href="#" title="Back to top" class="ink-bright-yellow pull-right back-to-top strong">/\ Back to top</a>')->close("p");
                $this->close("div");
                $clapOMeterBox = false;
                include($this->partial['hrcolours']);
            endif;
        endforeach;
    $this->close("div");
    require_once("{$this->partial['footer']}");
?></body>
</html>