<!DOCTYPE html>
<html lang="en-gb">
    <head><?php require_once("{$this->partial['header']}"); ?></head>
    <body class="paper-white ink-bright-black">
        <div id="content" class="container">
            <?php if(!empty($this->partial['navbar'])): ?>
                <?php require_once("{$this->partial['navbar']}"); ?>
            <?php endif; ?>
            <h1><?php echo print_r(http_response_code(), 1); ?> Error</h1>
            <h3>These are not the crap games that you are looking for</h3>
        </div>
        <hr />
        <?php require_once("{$this->partial['footer']}"); ?>
    </body>
</html>