<!DOCTYPE html>
<html lang="en-gb">
<?php 
    $this->open("head");
        require_once("{$this->partial['header']}");
    $this->close("head");
?><body class="paper-white ink-bright-black">
<?php
    $this->open("div", "content", "container");

        if(!empty($this->partial['navbar'])):
            require_once("{$this->partial['navbar']}");
        endif;

        if(!empty($this->flash->message)):
            $this->open("div", "flash", array("container", "flash"))
                ->p()->id("flash-message")->addClass(array("flash-bg", "green"))->closeElement()
                    ->text($this->flash->message)
                ->close("p")
            ->close("div");
        endif;

        $this->h(1, $this->header, "header")
        ->h(3, $this->subHeader, "sub_header");
        $hrCounter = 1;
        $hrDirection = 1;
        foreach($this->content as $key => $data):
            $this->h(4, "{$key}.&nbsp;{$data['name']}", $key, $data['class']);
            foreach($data['description'] as $content):
                $this->p()->closeElement()
                    ->text($content, true)
                ->close("p");
            endforeach;
            include($this->partial['hrcolours']);
        endforeach;
        
    $this->close("div");
    require_once("{$this->partial['footer']}");
?></body>
</html>