<!DOCTYPE html>
<html lang="en-gb">
	<?php 
    	$this->open("head");
			require_once("{$this->partial['header']}");
		$this->close("head");
    	$this->open("body");
    	   
    	   if(!empty($this->flash->message)){
    			$this->open("div", "flash", array("container", "flash"))
    				->p()->id("flash-message")->addClass(array("flash-bg", "green"))->closeElement()
    					->text($this->flash->message)
    				->close("p")
    			->close("div");
    		}
    		
    		$this->open("div", "content", "container")
    			->h(1, "Crap Gaming Competition 2018", "header")
    			->h(3, "Welcome to the 2018 Crap Graming Competition", "sub_header")
    			->p()->closeElement()->text("Have you ever wanted to make a game for your favourite Sinclair 8-bit computer? Now is your chance, and we want you to DO YOUR WORST!", true)->close("p")
    			->p()->closeElement()->text("See our <a href=\"{$this->host}/rules\" target=\"_blank\" rel=\"nofollow\">rules and regulations</a> before you submit your entry. If these are agreeable send your crap to <a href=\"mailto:shaun@square-circle.ZXco.uk\" rel=\"nofollow\">shaun@square-circle.co.uk</a> for evaluation!", true)->close("p")
    			->open("hr", '', null, true)
    		->close("div");
    		require_once("{$this->partial['footer']}");
    	$this->close("body");
    ?>
</html>