<!DOCTYPE html>
<html lang="en-gb">
<?php 
    $this->open("head");
        require_once("{$this->partial['header']}");
    $this->close("head");
?><body class="paper-white ink-bright-black">
<?php
    $this->open("div", "content", "container");
        $this->open("div", "", array("col-xs-12", "clearfix"));

            if(!empty($this->partial['navbar'])):
                require_once("{$this->partial['navbar']}");
            endif;

            if(!empty($this->flash->message)):
                $this->open("div", "flash", array("container", "flash", "col-xs-12", "clearfix"))
                    ->p()->id("flash-message")->addClass(array("flash-bg", "green"))->closeElement()
                        ->text($this->flash->message)
                    ->close("p")
                ->close("div");
            endif;

            $this->open("div", "home-content", array("col-xs-12", "col-md-8", "pull-left"));
                $this->h(1, $this->header, "header")
                ->h(3, $this->subHeader, "sub_header");
                $hrCounter = 1;
                $hrDirection = 1;
                foreach($this->content as $data):
                    $this->p()->addClass("pad-right-8")->closeElement()->text($data, true)->close("p");
                endforeach;
            $this->close("div");
            $this->open("div", "twitter-content", array("twitter-box", "col-xs-12", "col-md-4", "pull-right"));
                $this->text('<a href="https://twitter.com/CSSCGC2018?ref_src=twsrc%5Etfw" data-width="98%" data-height="auto" data-link-color="#00f" class="twitter-timeline" rel="nofollow">Tweets by CSSCGC2018</a>');
            $this->close("div");
            $this->open("div", "", array("col-xs-12", "clearfix"))
            ->close("div");
            include($this->partial['hrcolours']);
        $this->close("div")
    ->close("div");
    require_once("{$this->partial['footer']}");
?></body>
</html>