<!DOCTYPE html>
<html lang="en-gb">
<?php 
    $this->open("head");
        require_once("{$this->partial['header']}");
    $this->close("head");
    $clapOMeterBox = false;
?><body class="paper-white ink-bright-black">
<?php
    $this->open("div", "content", "container");

        if(!empty($this->partial['navbar'])):
            require_once("{$this->partial['navbar']}");
        endif;

        if(!empty($this->flash->message)):
            $this->open("div", "flash", array("container", "flash"))
                ->p()->id("flash-message")->addClass(array("flash-bg", "green"))->closeElement()
                    ->text($this->flash->message)
                ->close("p")
            ->close("div");
        endif;

        $this->h(1, $this->header, "header")->h(3, $this->subHeader, "sub_header");
        $hrCounter = 1;
        $hrDirection = 1;
        foreach($this->content as $content):
            $this->p()->id($this->lib->convertToHtmlId("{$content['title']}"))->addClass("h2")->closeElement()->text($content['title'])->close("p");
            $this->p()->addClass(array("h3", "ink-cyan"))->closeElement()->text("In a nut-shell: {$content['sub-header']}")->close("p");
            $this->p()->addClass(array("h5", "ink-cyan"))->closeElement()->text("Developer: {$content['developer']}")->close("p");
            
            if($content['yawn-sinclair-mega-game'] === true):
                $this->p()->addClass(array("h4", "ink-red"))->closeElement()->text("Yawn Sinclair MegaGame");
            endif;
            
            foreach($content['content'] as $reviewText):
                $this->p()->closeElement()->text("{$reviewText}")->close("p");
            endforeach;
            
            if($clapOMeterBox === false):
                $this->open("div", '', "col-xs-12");
                $clapOMeterBox = true;
            endif;
            
            $this->open("div", '', array("col-xs-12", "col-md-6", "pull-left"));
            $this->open("p", '', "review-screen-shot");
                $this->img(
                    "",
                    "{$content['screen-shot']['location']}{$content['screen-shot']['file-name']}",
                    "{$content['screen-shot']['width']}",
                    "{$content['screen-shot']['height']}",
                    "{$content['screen-shot']['alt']}",
                    "{$content['screen-shot']['class']} review-screen-shot"
                );
            $this->close("p");
            $this->close("div");
            
            foreach($content['cgc-clapometer'] as $key => $ratings):
                if($key == 'summary'):
                    $this->open("div", '', array("col-xs-12", "col-md-6", "pull-right"))->open("div", '', "clapometer-box")->p()->addClass("clapometer-summary")->closeElement()->text("<strong class=\"ink-blue\">" . ucFirst($key) . ":</strong>&nbsp;{$ratings}")->close("p");
                    continue;
                elseif($key != 'sundry'):
                    $this->p()->addClass("clapometer-ratings")->closeElement()->text("<strong class=\"ink-blue\">" . ucFirst($key) . ":</strong> &nbsp;");
                    $this->open("span", '', "pull-right");
                        for($i = 1; $i <= 10; $i++):
                            if($i <= $ratings):
                                $this->text("<i class=\"clapometer-point\">&nbsp;&nbsp;&nbsp;</i>");
                            else:
                            $this->text("<i class=\"clapometer-pointless\">&nbsp;&nbsp;&nbsp;</i>");
                            endif;
                        endfor;
                    $this->close("span");
                    $this->close("p");
                elseif($key == 'sundry'):
                    foreach($ratings as $textSundry):
                        $this->p()->addClass("ink-red")->closeElement()->text($textSundry)->close("p");
                    endforeach;
                    $this->close("div")->close("div");
                endif;
            endforeach;
            
            if($clapOMeterBox === true):
                $this->close("div");
                $clapOMeterBox = false;
                include($this->partial['hrcolours']);
            endif;
        endforeach;
    $this->close("div");
    require_once("{$this->partial['footer']}");
?></body>
</html>