<!DOCTYPE html>
<html lang="en-gb">
	<?php 
    	$this->open("head");
			require_once("{$this->partial['header']}");
		$this->close("head");
    	$this->open("body");
    	   
    	   if(!empty($this->flash->message)){
    			$this->open("div", "flash", array("container", "flash"))
    				->p()->id("flash-message")->addClass(array("flash-bg", "green"))->closeElement()
    					->text($this->flash->message)
    				->close("p")
    			->close("div");
    		}
    		
    		$this->open("div", "content", "container")
    			->h(1, $this->header, "header")
    			->h(3, $this->subHeader, "sub_header")
    		->close("div");
    		$this->open("div", "rules", "container");
    		foreach($this->rules as $key => $data):
    		    $this->p()->id("rule_{$key}")->closeElement()
    		        ->span("{$key}")->text("{$key}.&nbsp;")->close("span")
    		        ->text("{$data}")
    		    ->close("p");
    		endforeach;
    		$this->close("div");
    		require_once("{$this->partial['footer']}");
    	$this->close("body");
    ?>
</html>