<!DOCTYPE html>
<html lang="en-gb">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>Admin test page</title>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
		<meta name="author" content="Shaun Bebbington, James Sabin" />
		<meta name="twitter" content="@CSSCGC2018" />
		<script src="//code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
        <link href="http://cgc2018.local/css/normalize.css" rel="stylesheet">
        <link href="http://cgc2018.local/css/styles.css" rel="stylesheet">
	</head>
	<body class="paper-white">
		<div class="container">
			<div class="col-xs-12">
				<h1>Test admin</h1>
			</div>
		</div>
		<footer class="container">
			<p class="ink-bright-black">&copy; Sinclair Research 1982</p>
		</footer>
	</body>
</html>