<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title><?php echo $this->title ?? 'Retro Games Ltd && Donkeysoft'; ?></title>
<meta name="description" content="<?php echo $this->description ?? 'Make Cascade 50 quality computer software for your favourite Sinclair or compatible clone'; ?>" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
<?php if(!empty($this->metaData)): ?><?php echo $this->metaData; ?><?php else: ?>
<meta name="author" content="Shaun Bebbington, James Sabin" />
<meta name="twitter" content="@YearOfCodes" />
<?php endif; ?>
<?php echo $this->canonical ?? ''; ?>
<script src="//code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
<link href="<?php echo $this->host; ?>/css/normalize.css" rel="stylesheet">
<link href="<?php echo $this->host; ?>/css/styles.css" rel="stylesheet">
<link href="/img/apple-icon-57x57.png" sizes="57x57" rel="apple-touch-icon">
<link href="/img/apple-icon-60x60.png" sizes="60x60" rel="apple-touch-icon">
<link href="/img/apple-icon-72x72.png" sizes="72x72" rel="apple-touch-icon">
<link href="/img/apple-icon-76x76.png" sizes="76x76" rel="apple-touch-icon">
<link href="/img/apple-icon-114x114.png" sizes="114x114" rel="apple-touch-icon">
<link href="/img/apple-icon-120x120.png" sizes="120x120" rel="apple-touch-icon">
<link href="/img/apple-icon-144x144.png" sizes="144x144" rel="apple-touch-icon">
<link href="/img/apple-icon-152x152.png" sizes="152x152" rel="apple-touch-icon">
<link href="/img/apple-icon-180x180.png" sizes="180x180" rel="apple-touch-icon">
<link href="/img/android-icon-192x192.png" type="image/png" sizes="192x192" rel="icon">
<link href="/img/favicon-32x32.png" type="image/png" sizes="32x32" rel="icon">
<link href="/img/favicon-96x96.png" type="image/png" sizes="96x96" rel="icon">
<link href="/img/favicon-16x16.png" type="image/png" sizes="16x16" rel="icon">
<link href="/img/manifest.json" rel="manifest">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/img/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">