<nav class="navbar col-xs-12">
	<ul id="nav-items" class="nav-items clearfix">
        <li class="nav-item active"><a href="<?php echo $this->host; ?>/home.html" rel="nofollow">CGC Home</a></li>
		<li class="nav-item"><a href="<?php echo $this->host; ?>/challenges" rel="nofollow">Challenges</a></li>
		<li class="nav-item"><a href="<?php echo $this->host; ?>/entries" rel="nofollow">Entries</a></li>
		<li class="nav-item"><a href="<?php echo $this->host; ?>/news" rel="nofollow">Latest News</a></li>
		<li class="nav-item"><a href="<?php echo $this->host; ?>/results" rel="nofollow">Results</a></li>
		<li class="nav-item"><a href="<?php echo $this->host; ?>/reviews" rel="nofollow">Reviews</a></li>
		<li class="nav-item"><a href="<?php echo $this->host; ?>/rules" rel="nofollow">Rules</a></li>
	</ul>
</nav>