<nav class="navbar col-xs-12">
	<ul id="nav-items" class="nav-items clearfix">
        <li class="nav-item<?php if($this->segment == '' || strpos($this->segment, 'ome') !== false) :?> paper-blue<?php else: ?> paper-black<?php endif; ?>"><a href="<?php echo $this->host; ?>/home.html" class="ink-white" rel="nofollow">CGC Home</a></li>
		<li class="nav-item<?php if($this->segment == 'challenges') :?> paper-blue<?php else: ?> paper-black<?php endif; ?>"><a href="<?php echo $this->host; ?>/challenges" class="ink-white" rel="nofollow">Challenges</a></li>
		<li class="nav-item<?php if($this->segment == 'entries') :?> paper-blue<?php else: ?> paper-black<?php endif; ?>"><a href="<?php echo $this->host; ?>/entries" class="ink-white" rel="nofollow">Entries</a></li>
		<li class="nav-item<?php if($this->segment == 'news') :?> paper-blue<?php else: ?> paper-black<?php endif; ?>"><a href="<?php echo $this->host; ?>/news" class="ink-white" rel="nofollow">Latest News</a></li>
		<!-- <li class="nav-item<?php if($this->segment == 'results') :?> paper-blue<?php else: ?> paper-black<?php endif; ?>"><a href="<?php echo $this->host; ?>/results" class="ink-white" rel="nofollow">Results</a></li> -->
		<li class="nav-item<?php if($this->segment == 'reviews') :?> paper-blue<?php else: ?> paper-black<?php endif; ?>"><a href="<?php echo $this->host; ?>/reviews" class="ink-white" rel="nofollow">Reviews</a></li>
		<li class="nav-item<?php if($this->segment == 'rules') :?> paper-blue<?php else: ?> paper-black<?php endif; ?>"><a href="<?php echo $this->host; ?>/rules" class="ink-white" rel="nofollow">Rules</a></li>
	</ul>
</nav>